### ISSUE TITLE
Reading file with node configuration

### ISSUE THREAD

**Issue by nmenshov** [qoollo/bob#10]
name: node0
address: 127.0.0.1:4401
disks:
    - disk1: /opt/disk1
    - disk2: /opt/disk2
logging: debug

**Comment by agend** [comment]
let's `address` -> `listen` or `bind`
Also we need to add mapping for `virtual path` to physical one like: `/opt/disk`' -> `/dev/sda`

**Comment by nmenshov** [comment]
name: node0
disks:
    - disk1: /dev/sda1   # physical path.
    - disk2: /dev/sda2
logging: debug

Map disks names with disks from cluster config

**Comment by nmenshov** [comment]
name: node0
logging: debug

simplify config
