### ISSUE TITLE
Consider using 'metrics' crate for performance counters

### ISSUE THREAD

**Issue by ikopylov** [qoollo/bob#129]
This crate doesn't support Graphite out of the box, so it is required to implement metrics delivery by hand

**Comment by Justarone** [comment]
09.12 - 16.12: 6h (fix review issues, merge with actual master version (with additional metrics, first attempt to rewrite Channel and TcpStream on async versions(exporter))

**Comment by Justarone** [comment]
30.12 - 15.01 - 6h (finally rewrote no async model + local tests)

**Comment by Justarone** [comment]
04.02 - 3h (hotfix of metrics crate bug (with RefCell))

**Comment by Justarone** [comment]
05.02: 0.5h (remove wrappers at all from metrics exporter channel sender)
