### ISSUE TITLE
Add performance counter to track the memory occupied by indexes

### ISSUE THREAD

**Issue by ikopylov** [qoollo/bob#141]
This task depends on pearl API: https://github.com/qoollo/pearl/issues/68

**Comment by Justarone** [comment]
16.12 - 23.12: 4.5h (1.5h - async channel + attempt to write something like `fold` for aggregation of results of async methods of `holders` (failed attempt), 3h - index_memory template + attempt to impl `Future` for `RetrySocket` or change `std::net::TcpStream` on `tokio::net::TcpStream` (need to discuss it))

**Comment by Justarone** [comment]
20.01 - 30.01 - 1h (merge master into metrics and using Pearl API to track memory)

**Comment by Justarone** [comment]
closed by #137
