### ISSUE TITLE
Allow to configure the location of alien directory

### ISSUE THREAD

**Issue by ikopylov** [qoollo/bob#146]
It would be nice to be able to place `alien` directory at different disk

**Comment by Justarone** [comment]
20.01 - 30.01 - 2h (write code and test)

**Comment by Justarone** [comment]
30.01 - 1h (remake, fix review issues)

**Comment by Justarone** [comment]
31.01 - 0.5h (fix review issue)

**Comment by Justarone** [comment]
04.02 - 1h (some tests on alien configuration and further alien records processing)
