### ISSUE TITLE
Detect physical disk failures and stop using it when it is down

### ISSUE THREAD

**Issue by ikopylov** [qoollo/bob#149]
Do not try to endlessly initialize Perl on a dead disk.

Related to https://github.com/qoollo/bob/issues/111

**UPDATE:**
Write information about all disk failures and recoveries to a file. We need at least a disk name + a failure/recovery timestamp. In addition, it may contain additional information about the cause of the failure.

**Comment by Justarone** [comment]
20.01 - 30.01 - 14h (research: tokio-inotify/tokio-udev/inotify crates experiments, checking other methods of detecting disk errors, discussions about solutions of this problem with other collaborators and etc.)

**Comment by Justarone** [comment]
04.02 - 1h (disk controller state work)

**Comment by Justarone** [comment]
10.02 - 7h (disk controller first (bad) version: monitor task and state (wrong place of structure))
20.02 - 6.5h (first version of disk controller individual structure)
21.02 - 2.5h (first version of disk_controller with recovery)
22.02 - 2.5h (refactoring of disk controller and tests)
24.02 - 7h (DiskController: fix review issues and conflicts with master, fix semaphore and concurrency logic and tests)
