### ISSUE TITLE
Implement an authorization and authentication mechanism 

### ISSUE THREAD

**Issue by ikopylov** [qoollo/bob#183]
To make Bob a production ready solution, we must implement authorization and authentication. 

It would be good to implement a permission based policy. Possible permissions are:
1. Read records
2. Write records
3. REST API basic read-only access (get cluster configuration and execute other read-only informational methods)
4. REST API access for updates

User configuration can be stored in a file. I propose to implement it in a similar way to ClickHouse: https://github.com/ClickHouse/ClickHouse/blob/master/programs/server/users.xml. This file will contain a list of profiles (aka roles) + list of users. Each role must have a list of permissions. Each user must have a password and an assigned role.

**Comment by agend** [comment]
build into bob node or via gateway?

**Comment by ikopylov** [comment]
The current idea is to implement it directly in Bob. But we should definitely analyze the pros and cons of both solutions before making a final decision

**Comment by ikopylov** [comment]
Current plan: study the authorization and authentication mechanism in ClickHouse and in other key-value storages

**Comment by ikopylov** [comment]
Redis has limited auth support: https://redis.io/topics/security
MinIO has full auth support: https://docs.min.io/docs/minio-multi-user-quickstart-guide.html

Some info about auth in ClickHouse: https://clickhouse.tech/docs/ru/operations/access-rights/

**Comment by ikopylov** [comment]
Closed via https://github.com/qoollo/bob/pull/217
