### ISSUE TITLE
Check out how Bob works with large records

### ISSUE THREAD

**Issue by ikopylov** [qoollo/bob#235]
Run multiple bobp with record sizes:
1. 10Mb
2. 100Mb
3. 1Gb
4. 4Gb

We need to understand how Bob works with really large records. 
Main questions: 
1. Will writing and reading be stable? 
2. What will be the write and read speed?

**Comment by alexprof** [comment]
| Test # | Payload Size | Count | Write Time | Read Time | RPS (Write) | RPS (Read) | Threads |
|--------|--------------|-------|------------|-----------|-------------|------------|---------|
| 1      | 10 Mb        | 20000 | 3002 s     | 1895 s    | 6           | 10         | 8       |
| 2      | 100 Mb       | 2000  | 3076 s     | 1866 s    | 0           | 1          | 8       |
| 3      | 1 Gb         | 200   | 7462 s     | 5951 s    | 0           | 0          | -       |
| 4      | 2 Gb         | 100   | 9162 s     |           | 0           |            | -       |
