### ISSUE TITLE
Checksum mismatch on read when record size is close to 2 GB 

### ISSUE THREAD

**Issue by ikopylov** [qoollo/bob#278]
Record size ~2047Mb. This could also be due to a write error (e.g. some data was not written to disk). 

```
2021-08-02 11:43:20         pearl::record:134 ERROR Error {
    kind: Validation(
        "wrong data checksum 1734825071 vs 774327065",
    ),
}
```

**Comment by Boneyan** [comment]
Performed 150 puts of 2146436000 byte records (~2047mib) and 150 gets of the records via bobp, no errors occurred. Seems like this bug scenario is no longer actual.
