### ISSUE TITLE
BobPartitionRemover: add feature to remove old BLOBs based on free disk space

### ISSUE THREAD

**Issue by ikopylov** [qoollo/bob#284]
If free space on disk is less than the configured threshold, BobPartitionRemover should trigger the deletion of old BLOBs so that the free space becomes above the threshold

**Comment by idruzhitskiy** [comment]
Will be implemented in https://github.com/qoollo/bob-tools/pull/16

**Comment by ikopylov** [comment]
Closed via https://github.com/qoollo/bob-tools/pull/16
