### ISSUE TITLE
Do not open second file descriptor for BLOBs

### ISSUE THREAD

**Issue by ikopylov** [qoollo/bob#320]
Related issue #264

Second descriptor is used to call `fsync`, but instead we can use main descriptor for this task (or even open a new descriptor each time we need to sync and then close it)

**Comment by idruzhitskiy** [comment]
Linked pearl [issue (#124)](https://github.com/qoollo/pearl/issues/124)

**Comment by ikopylov** [comment]
Closed via https://github.com/qoollo/pearl/pull/125
