### ISSUE TITLE
There are conditions when data written to aliens are not read after that

### ISSUE THREAD

**Issue by ikopylov** [qoollo/bob#502]
@vovac12 reproduced this in his tests. Additional investigation is required

**Comment by ikopylov** [comment]
This reproduces during the following test:
1. Run 4 nodes cluster whith 2 replicas
2. Turn off one node
3. Write 250k items
4. Turn off second node
5. Write 250k items
6. Turn off third node
7. Write 250k items
8. Turn on all nodes
9. Read all items. Normally, they all should be read. Actual behaviour: large number of items are not available

**Comment by idruzhitskiy** [comment]
Test was incorrectly conducted, bug is not confirmed

**Comment by ikopylov** [comment]
Bug is not confirmed
