### ISSUE TITLE
IntegrationTest fails on specififc cluster configuration

### ISSUE THREAD

**Issue by ikopylov** [qoollo/bob#749]
Configuration: 1 node, 1 vdisk, 1 vdisk replica

**Comment by Ziktorin** [comment]
Probably the problem is that default value for quorum is 2 and is not configurable in workflow dispatch. It should be either set to 1 as a default or be added to workflow dispatch

**Comment by ikopylov** [comment]
Please, add quorum as a parameter to workflow dispatch

**Comment by ikopylov** [comment]
Closed via https://github.com/qoollo/bob/pull/754
