### ISSUE TITLE
Additional performance counters

### ISSUE THREAD

**Issue by ikopylov** [qoollo/bob#98]
Add several useful performance counters:
1. Counters to track `exists` method performance: total request count, failed request count, request per second, elapsed time
2. Additional counters for `get` and `put`: failed request count
3. Counter to track total number of blobs
4. Counter to track number of blobs in `alien` directory
5. Counter to track `Bob` status (this will allow to identify stuck during startup): 0 - starting, 1 - fully started
6. Counters to track side nodes to which the current node connected (should help to detect network issues): one counter per node with the number of connections to that node
7. Counter to track the number of lost/inaccessible blobs (should help to identify disk fault)

**Comment by Justarone** [comment]
Tap.
